name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: pnpm

      - name: Install dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Install Chromium
        run: pnpm exec playwright install chromium --with-deps

      - name: Run Playwright tests
        run: pnpm exec playwright test

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
